### ISSUE TITLE
stdout maxbuffer exceeded error

### ISSUE THREAD

**Issue by vince-geekcore** [hoffi/gulp-msbuild#45]
Hi,

When setting the verbosity of msbuild output to something else then quiet or minimum my build fails most of the time returning a 'stdout maxbuffer exceeded' error because it outputs too much data. Unfortunately i need this data to diagnose any issues or build errors/warnings. Is this something that can/needs to be fixed inside gulp-msbuild? Apparently the default buffer size is used: https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback
https://github.com/SaschaGalley/grunt-phpunit/issues/29 (similar issue)

Thanks in advance

**Comment by hoffi** [comment]
Hi, 

i don't think it's the same issue because i use `child_process.spawn` instead of `child_process.exec`, [because of this maxbuffer issue](https://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html).

Do you use the latest version of gulp-msbuild and what configuration do you use?
Does it help when you disable `stdout` and use [file logging](https://github.com/hoffi/gulp-msbuild#fileloggerparameters) instead?

**Comment by vince-geekcore** [comment]
Hi hoffi,

Yes.. somehow i had an older version that didn't get updated. Have not yet encountered this on the latest version. Sorry about that. This can be closed/removed.

**Comment by hoffi** [comment]
Hi, no problem :)
